//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public long Id { get; set; }
        public int UserId { get; set; }
        public string Text { get; set; }
        public System.DateTime Time { get; set; }
        public Nullable<System.Guid> SessionId { get; set; }
    
        public virtual User User { get; set; }
    }
}
