//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.Students = new HashSet<Student>();
        }
    
        public int Id { get; set; }
        public Nullable<int> HeadId { get; set; }
        public string Motto { get; set; }
    
        public virtual Student Head { get; set; }
        public virtual ICollection<Student> Students { get; set; }
    }
}
